version: '3.3'
services:
  web:
    build: .
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
    links:
      - db
    networks:
      - default
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: reto_2
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - persistent:/var/lib/mysql
    networks:
     - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
volumes:
  persistent: