version: '3'

services:

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../web:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reto_2
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - persistent:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8079:80"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: reto_2
volumes:
  persistent: