version: '3.3'
services:
  web:
    image: php:7.3-apache
    container_name: php73
    volumes:
      - ../web:/var/www/html
    ports:
      - 8080:80
  db:
    image: mysql
    container_name: mysqlDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: reto_2
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: reto_2
    volumes:
      - persistent:/var/lib/mysql
    networks:
     - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: reto_2
volumes:
  persistent: